Fix AttributeError
Fixed AttributeError: 'Parser' object has no attribute 'get_options'
This occurs because change of Parser algorithm and the functions name too
See commit 9826b3483a45f5b57a4432b31bf94e07e5b3a672

Signed-off-by: Aziz Ridhwan <fwindows345@gmail.com>